import { Js2tronic } from "./class/Js2tronic";

import { Stuffable } from "./enum/Stuffable";
import { CartridgeVariant } from "./enum/CartridgeVariant";
import { DesertVariant } from "./enum/DesertVariant";
import { DirtVariant } from "./enum/DirtVariant";
import { MoonVariant } from "./enum/MoonVariant";
import { OneWayVariant } from "./enum/OneWayVariant";
import { RobotVariant } from "./enum/RobotVariant";
import { SaurusVariant } from "./enum/SaurusVariant";
import { ShipVariant } from "./enum/ShipVariant";
import { RotationAngle } from "./enum/RotationAngle";
import { GravityState } from "./enum/GravityState";

console.log(GravityState.FALL);
const j2t: Js2tronic = new Js2tronic();
console.log(j2t);
let test = j2t.block.BrickBlue();
console.log(test);
test.pushToBackground().groupTo(331144).stuffWith(Stuffable.GRUBBY);
console.log(test);
let cartrdige = j2t.block.Cartridge();
cartrdige.spriteVariant(CartridgeVariant.FLOOR);
console.log(cartrdige);
let desert = j2t.block.Desert();
desert.spriteVariant(DesertVariant.TOP_ORANGE);
console.log(desert);
let dirt = j2t.block.Dirt();
dirt.spriteVariant(DirtVariant.TOP_LONG);
console.log(dirt);
let moon = j2t.block.Moon();
moon.spriteVariant(MoonVariant.TOP_BUMP);
console.log(moon);
let oneWay = j2t.block.OneWay();
oneWay.spriteVariant(OneWayVariant.FILLER);
console.log(oneWay);
let robot = j2t.block.Robot();
robot.spriteVariant(RobotVariant.BOTTOM_LEFT_CORNER);
console.log(robot);
let saurus = j2t.block.Saurus();
saurus.spriteVariant(SaurusVariant.FILLER_THREE_SCALES);
console.log(saurus);
let ship = j2t.block.Ship();
ship.spriteVariant(ShipVariant.FILLER_LEFT_TOP_RIGHT_NOTCHES_VARIANT_A);
console.log(ship);
let fertbox = j2t.block.FertBox();
fertbox.rotateTo(RotationAngle.UPSIDE_DOWN);
console.log(fertbox);
let gravBlock = j2t.block.GravityBlock();
gravBlock.label("test label").pushToBackground();
console.log(gravBlock);
console.log(gravBlock.tronicnum);
let iceblock = j2t.block.IceBlock();
console.log(iceblock);
iceblock.groupTo(221144).stuffWith(Stuffable.GRUBBY);
console.log(iceblock);
let InvisableBlock = j2t.block.InvisableBlock();
InvisableBlock.rotateTo(RotationAngle.COUNTER_CLOCKWISE).stuffWith(Stuffable.BOOT).groupTo(122435);
console.log(InvisableBlock);
let KaizoBlock = j2t.block.KaizoBlock();
KaizoBlock.rotateTo(RotationAngle.COUNTER_CLOCKWISE).stuffWith(Stuffable.BOOT).groupTo(122435);
console.log(KaizoBlock);
let MetalBlock = j2t.block.MetalBlock();
MetalBlock.groupTo(54123);
console.log(MetalBlock);
let QuestionBlock = j2t.block.QuestionBlock();
QuestionBlock.rotateTo(RotationAngle.COUNTER_CLOCKWISE).stuffWith(Stuffable.BOOT).groupTo(122435);
console.log(QuestionBlock);
let FloatBlock = j2t.block.FloatBlock();
FloatBlock.rotateTo(RotationAngle.COUNTER_CLOCKWISE);
console.log(FloatBlock);
let ChainBend = j2t.block.ChainBend();
ChainBend.pushToBackground().rotateTo(RotationAngle.COUNTER_CLOCKWISE);
console.log(ChainBend);
let Door = j2t.block.Door();
Door.groupTo(25566).destinationDoor(224466).label("test label door");
console.log(Door);